#!/bin/sh
set -e

file=$1
type=$2
if [ "$type" != "commit" ]; then
    temp=`tempfile`
    cp $file $temp
    git branch-name | perl -ne 'print "refs #$1 " if m!^t/([0-9]+)!' > $file
    [ "$type" != "message" ] && echo >> $file
    cat $temp >> $file
    rm -f $temp
fi
